// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjdEcf79borHiGONut4q_edtD8JPXGLM',
    appId: '1:84112273308:web:e85e6390d845f7b786e259',
    messagingSenderId: '84112273308',
    projectId: 'mobile-final-app-2437a',
    authDomain: 'mobile-final-app-2437a.firebaseapp.com',
    storageBucket: 'mobile-final-app-2437a.appspot.com',
    measurementId: 'G-GYQ7WJ6BCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDANCVfj9hnqcfbJyVtM_nDKSQgrf82h5w',
    appId: '1:84112273308:android:e43b7c7a21c3d46f86e259',
    messagingSenderId: '84112273308',
    projectId: 'mobile-final-app-2437a',
    storageBucket: 'mobile-final-app-2437a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1395F3st8zgkImy5BRHNGeyW82eNQDWo',
    appId: '1:84112273308:ios:e0aca69d2da4cd2a86e259',
    messagingSenderId: '84112273308',
    projectId: 'mobile-final-app-2437a',
    storageBucket: 'mobile-final-app-2437a.appspot.com',
    iosClientId: '84112273308-j1mdt4b2h06ibu1vk64tjvuie9h7h4jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalprojectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1395F3st8zgkImy5BRHNGeyW82eNQDWo',
    appId: '1:84112273308:ios:e0aca69d2da4cd2a86e259',
    messagingSenderId: '84112273308',
    projectId: 'mobile-final-app-2437a',
    storageBucket: 'mobile-final-app-2437a.appspot.com',
    iosClientId: '84112273308-j1mdt4b2h06ibu1vk64tjvuie9h7h4jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalprojectApp',
  );
}
